# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Regenerate lib/codemap.js and lib/models.js from the notebooks and MuJoCo models.

    uv run tools/sync.py                  # rewrite both files if they changed
    uv run tools/sync.py --check          # exit 1 if either file is stale or a data-code does not resolve
    uv run tools/sync.py --list 01_optimization_fundamentals.py   # the references one file offers

lib/codemap.js holds window.CODEMAP = {"FILE:name": {file, start, end, src, doc, marimo}} for
every function and class in tutorial/*.py and tutorial/labs/**/*.py that sits at top level or
one level inside an @app.cell function. FILE is relative to tutorial/, start and end are 1-based
line numbers in that file (decorators included), src is the dedented source, doc the docstring
("" when there is none), and marimo says whether FILE is a marimo notebook. When one file
defines a name twice, the first definition is kept and a warning is printed.

lib/models.js holds window.MODELS = {stem: xml} for every tutorial/models/*.xml.

Both files are written atomically (temporary file + rename), so several agents may run this at
once. Standard library only.
"""

import argparse
import ast
import json
import os
import re
import sys
import tempfile
import textwrap
from html.parser import HTMLParser
from pathlib import Path

SLIDES = Path(__file__).resolve().parent.parent
TUTORIAL = SLIDES.parent
LIB = SLIDES / "lib"
CODEMAP = LIB / "codemap.js"
MODELS = LIB / "models.js"

# A line comment: the globs in {what} contain "*/", which would end a block comment.
HEADER = "// Generated by tools/sync.py from {what}. Do not edit; run `uv run tools/sync.py`.\n"


def warn(msg):
    print(f"sync.py: warning: {msg}", file=sys.stderr)


def source_files():
    files = sorted(TUTORIAL.glob("*.py"))
    labs = TUTORIAL / "labs"
    if labs.is_dir():
        files += sorted(p for p in labs.rglob("*.py") if "__pycache__" not in p.parts)
    return files


def _decorator_name(d):
    """'app.cell' for @app.cell and @app.cell(hide_code=True); '' for anything unusual."""
    if isinstance(d, ast.Call):
        d = d.func
    parts = []
    while isinstance(d, ast.Attribute):
        parts.append(d.attr)
        d = d.value
    if isinstance(d, ast.Name):
        parts.append(d.id)
        return ".".join(reversed(parts))
    return ""


DEFS = (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)


def definitions(tree):
    """Yield the defs to index: top level (except marimo cells) and one level inside cells."""
    for node in tree.body:
        if not isinstance(node, DEFS):
            continue
        decos = {_decorator_name(d) for d in node.decorator_list}
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and "app.cell" in decos:
            for inner in node.body:
                if isinstance(inner, DEFS):
                    yield inner
        else:
            yield node  # plain module function / class, @app.function, @app.class_definition


def index_file(path: Path):
    rel = path.relative_to(TUTORIAL).as_posix()
    text = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(text, filename=str(path))
    except SyntaxError as e:
        warn(f"{rel}: syntax error at line {e.lineno}; skipped")
        return {}
    lines = text.splitlines()
    marimo = bool(re.search(r"^app\s*=\s*marimo\.App\(", text, re.M))
    out = {}
    for node in definitions(tree):
        key = f"{rel}:{node.name}"
        start = min([node.lineno] + [d.lineno for d in node.decorator_list])
        end = node.end_lineno
        if key in out:
            warn(f"{rel}: '{node.name}' is defined again at line {start}; keeping the definition at line {out[key]['start']}")
            continue
        src = textwrap.dedent("\n".join(lines[start - 1 : end])) + "\n"
        out[key] = {
            "file": rel,
            "start": start,
            "end": end,
            "src": src,
            "doc": ast.get_docstring(node) or "",
            "marimo": marimo,
        }
    return out


def build_codemap():
    entries = {}
    for path in source_files():
        entries.update(index_file(path))
    body = ",\n".join(f"{json.dumps(k)}: {json.dumps(v, ensure_ascii=True)}" for k, v in sorted(entries.items()))
    js = HEADER.format(what="tutorial/*.py and tutorial/labs/**/*.py")
    js += "window.CODEMAP = {\n" + body + ("\n" if body else "") + "};\n"
    return js, entries


def build_models():
    models = {}
    mdir = TUTORIAL / "models"
    for p in sorted(mdir.glob("*.xml")) if mdir.is_dir() else []:
        models[p.stem] = p.read_text(encoding="utf-8")
    body = ",\n".join(f"{json.dumps(k)}: {json.dumps(v, ensure_ascii=True)}" for k, v in models.items())
    js = HEADER.format(what="tutorial/models/*.xml")
    js += "window.MODELS = {\n" + body + ("\n" if body else "") + "};\n"
    return js, models


def write_atomic(path: Path, text: str):
    """Replace path with text through a temporary file in the same folder; skip if unchanged."""
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        os.chmod(tmp, 0o664)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise
    return True


class CodeRefs(HTMLParser):
    """Collect (line, ref) for every data-code attribute in an HTML file."""

    def __init__(self):
        super().__init__()
        self.refs = []

    def handle_starttag(self, tag, attrs):
        for k, v in attrs:
            if k == "data-code" and v:
                line = self.getpos()[0]
                self.refs += [(line, r) for r in re.split(r"[,\s]+", v) if r]

    handle_startendtag = handle_starttag


def html_pages():
    pages = sorted(SLIDES.glob("[0-9][0-9]_*.html"))
    if (SLIDES / "template.html").exists():
        pages.append(SLIDES / "template.html")
    demos = SLIDES / "tools" / "demos"
    if demos.is_dir():
        pages += sorted(demos.glob("*.html"))
    return pages


def unresolved(entries):
    bad = []
    for page in html_pages():
        p = CodeRefs()
        p.feed(page.read_text(encoding="utf-8", errors="replace"))
        for line, ref in p.refs:
            if ref not in entries:
                bad.append(f"{page.relative_to(SLIDES)}:{line}: data-code '{ref}' does not resolve")
    return bad


def list_refs(arg, entries):
    p = Path(arg)
    cands = [p, TUTORIAL / arg, Path.cwd() / arg]
    rel = None
    for c in cands:
        if c.exists():
            try:
                rel = c.resolve().relative_to(TUTORIAL).as_posix()
                break
            except ValueError:
                pass
    rel = rel or arg
    hits = {k: v for k, v in entries.items() if v["file"] == rel}
    if not hits:
        sys.exit(f"sync.py: no definitions indexed for {arg!r} (tutorial-relative name: {rel!r})")
    for k, v in sorted(hits.items(), key=lambda kv: kv[1]["start"]):
        doc = v["doc"].strip().splitlines()[0] if v["doc"].strip() else ""
        print(f"{k:60s} {v['start']:>5d}-{v['end']:<5d} {doc}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail on stale files or unresolved data-code")
    ap.add_argument("--list", metavar="FILE", help="print the references FILE offers")
    args = ap.parse_args()

    code_js, entries = build_codemap()
    models_js, models = build_models()

    if args.list:
        list_refs(args.list, entries)
        return

    if args.check:
        problems = []
        for path, text in ((CODEMAP, code_js), (MODELS, models_js)):
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                problems.append(f"{path.relative_to(SLIDES)} is stale (run uv run tools/sync.py)")
        problems += unresolved(entries)
        for m in problems:
            print(f"ERROR  {m}")
        print(f"sync.py --check: {len(entries)} definitions, {len(models)} models, {len(problems)} problems")
        sys.exit(1 if problems else 0)

    wrote = [path.name for path, text in ((CODEMAP, code_js), (MODELS, models_js)) if write_atomic(path, text)]
    print(f"sync.py: {len(entries)} definitions -> lib/codemap.js, {len(models)} models -> lib/models.js"
          + (f" (rewrote {', '.join(wrote)})" if wrote else " (both up to date)"))
    for m in unresolved(entries):
        warn(m)


if __name__ == "__main__":
    main()
